[package]
name = "rayball"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = { version = "0.4", features = ["audio"] }
log = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
simplelog = "0.12.2"

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'
strip = true
