name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git --depth 1
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Install Rust WASM
        run: rustup target add wasm32-unknown-emscripten

      - name: Build Game
        run: |
          source ./emsdk/emsdk_env.sh

          export EMCC_CFLAGS="-O3 -sUSE_GLFW=3 -sASSERTIONS=1 -sWASM=1 -sASYNCIFY -sGL_ENABLE_GET_PROC_ADDRESS=1"
          export BINDGEN_EXTRA_CLANG_ARGS="-I${EMSDK}/upstream/emscripten/cache/sysroot/include"
          export RUSTFLAGS='-C link-arg=-sUSE_GLFW=3 -C link-arg=-sASYNCIFY -C link-arg=-sEXPORTED_RUNTIME_METHODS=["ccall","cwrap","HEAPF32","HEAPU8"] -C link-arg=-sALLOW_MEMORY_GROWTH=1 -C link-arg=--preload-file -C link-arg=assets'

          cargo build --target wasm32-unknown-emscripten --release

          mkdir -p dist
          cp target/wasm32-unknown-emscripten/release/rayball.wasm dist/
          cp target/wasm32-unknown-emscripten/release/rayball.js dist/
          cp target/wasm32-unknown-emscripten/release/deps/rayball.data dist/
          cp index.html dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
